language: cpp
env:
    matrix:
      - OS=el DIST=6
      - OS=el DIST=7
      - OS=el DIST=8
      - OS=fedora DIST=29
      - OS=fedora DIST=30
      - OS=fedora DIST=31
      - OS=ubuntu DIST=xenial
      - OS=ubuntu DIST=bionic
      - OS=ubuntu DIST=disco
      - OS=ubuntu DIST=eoan
      - OS=debian DIST=jessie
      - OS=debian DIST=stretch
      - OS=debian DIST=buster
      - OS=debian DIST=sid
      - OS=ubuntu DIST=xenial ARCH=i386
      - OS=ubuntu DIST=bionic ARCH=i386
      - OS=ubuntu DIST=disco ARCH=i386
      - OS=ubuntu DIST=eoan ARCH=i386
      - OS=debian DIST=jessie ARCH=i386
      - OS=debian DIST=stretch ARCH=i386
      - OS=debian DIST=buster ARCH=i386
      - OS=debian DIST=sid ARCH=i386
  include:
  - os: linux
    before_install:
    - sudo ./prerequisites.sh
    compiler:
    - gcc
    script:
    - make

