language: c++
matrix:
  - dist: precise
    compiler: clang
    os: linux
    sudo: required
  - dist: xenial
    compiler: gcc
    os: linux
    sudo: required
  - dist: xenial
    compiler: clang
    os: linux
    sudo: required
  - dist: bionic
    complier: clang
    os: linux
    sudo: required
  - dist: bionic
    complier: gcc
    os: linux
    sudo: required

