language: c++

before_install:
        - sudo ./prerequisites.sh

script:
        - make
        - sudo make install

matrix:
  - dist: bionic
    complier: clang
    os: linux
    sudo: required
  - dist: bionic
    complier: gcc
    os: linux
    sudo: required

