language: cpp
  include:
  - os: linux
    matrix: 
    - include:
        - xenial
        - bionic
        - precise
        - trusty
    before_install:
    - sudo ./prerequisites.sh
    compiler:
    - matrix
      - gcc
      - clang
    script:
    - make

