language: cpp
  include:
  - os: linux
    - dist: xenial
    - dist: bionic
    - dist: precise
    - dist: trusty
    before_install:
    - sudo ./prerequisites.sh
    compiler:
    - matrix
      - gcc
      - clang
    script:
    - make

